on:
  pull_request:
    branches:
    - main

env:
  CI: true

jobs:
  run_npm_test:
    strategy:
      matrix:
        # Available OS's: https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners
        os: [ubuntu-20.04]

        node-version: [16.x, 14.x]
    runs-on: ${{ matrix.os }}
    name: Run tests on all PRs to 'main'
    steps:
        # Setup
      - name: Checkout repo
        uses: actions/checkout@v3.5.2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/
          scope: '@solid'
      - run: npm ci
      - run: npm test
